### ISSUE TITLE
Unexpected behaviour for intersection of adjacent intervals

### ISSUE THREAD

**Issue by leamingrad** [Superbird11/ranges#7]
Firstly, thanks for publishing this library - it has been useful so far. I've noticed some strange behaviour for the intersection of intervals that are adjacent but disjoint.

From the documentation of `Range.intersection`:

> Returns a range representing the intersection between this range and the given range, or None if the ranges don’t overlap at all.

However, if you are trying to find the intersection of disjoint adjacent intervals, you actually get an empty interval at the shared boundary, as follows:

```python
>>> a = Range(1, 4)  # [1, 4)
>>> b = Range(4, 6)  # [4, 6)
>>> a.isdisjoint(b)
True
>>> a.intersection(b)
Range(4, 4)  # [4, 4)
>>> a.intersection(b).isempty
```

Is this intentional - from the look of code [here](https://github.com/Superbird11/ranges/blob/a6d77871fa620b8dde9a8ee19279c1b29cb09ea7/ranges/ranges.py#L273) I think it is, but if so what is the rationale behind it?

It feels like it would be more intuitive to return `None` for all disjoint ranges, so that `a.intersection(b) == None or not a.isdisjoint(b)` holds for all ranges?

**Comment by Superbird11** [comment]
This was intentional, yes, but in retrospect it is more intuitive to return `None`. I think the reason I didn't initially is because it's possible to manually create an empty range, and having `.intersection()` produce one would be consistent. I've made the change anyway, `None` makes more sense, and since `Range.__bool__` checks for emptiness anyway this shouldn't break most code.
